---
- name: Interact with Nautobot API
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Debug Nautobot URL
      debug:
        msg: "Connecting to Nautobot at {{ lookup('env', 'NAUTOBOT_URL') }}"

    - name: Fetch data from Nautobot
      uri:
        url: "{{ lookup('env', 'NAUTOBOT_URL') }}/api/dcim/devices/"
        method: GET
        headers:
          Authorization: "Token {{ lookup('env', 'NAUTOBOT_TOKEN') }}"
          Accept: application/json
      register: response

    - name: Display response
      debug:
        var: response.json   

        
plugin: networktocode.nautobot.inventory
api_endpoint: !env NAUTOBOT_URL
token: !env NAUTOBOT_TOKEN
validate_certs: true

# Query devices and virtual machines
query:
  devices:
    name:
    primary_ip4:
      host:
    platform:
      name:
      napalm_driver:
    device_role:
      name:
      slug:
    site:
      name:
      slug:
    location:
      name:
    tenant:
      name:
    tags:
      name:
    status:
      value:
    serial:
  virtual_machines:
    name:
    primary_ip4:
      host:
    platform:
      name:
    tenant:
      name:
    tags:
      name:

# Group devices dynamically - USE VALID VALUES ONLY
group_by:
  - device_roles
  - platforms
  - locations
  - tenants
  - tags
  - status

# Set ansible_host to primary IP
compose:
  ansible_host: primary_ip4.host | default(primary_ip6.host)
  ansible_network_os: platform.napalm_driver
